# Generated by Django 2.0.6 on 2025-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20251204_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election_year',
            field=models.IntegerField(default=2018),
        ),
    ]
