# Generated by Django 2.0.6 on 2018-06-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('size', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=1)),
                ('period', models.CharField(choices=[('TDY', 'today'), ('WKK', 'week'), ('MNT', 'month'), ('YAR', 'year')], max_length=2)),
            ],
        ),
    ]
