# Generated by Django 2.0.6 on 2018-06-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_word_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='period',
            field=models.CharField(choices=[('TDY', 'today'), ('WKK', 'week'), ('MNT', 'month'), ('YAR', 'year')], max_length=255),
        ),
    ]
