# Generated by Django 2.0.6 on 2018-06-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Category'),
        ),
    ]
