# Generated by Django 2.0.6 on 2018-06-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='query_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
