# Generated by Django 2.0.6 on 2018-07-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_auto_20180704_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=1)),
                ('real_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('-size',)},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('-size',)},
        ),
        migrations.AddField(
            model_name='sizehistory',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='elections.Candidate'),
        ),
    ]
