# Generated by Django 2.0.6 on 2018-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_auto_20180717_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
