# Generated by Django 2.0.6 on 2018-08-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_word_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('where', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('round', models.PositiveIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
