# Generated by Django 2.0.6 on 2018-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_importantdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='labels',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
