# Generated by Django 2.0.6 on 2018-08-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_candidate_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering_factor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
