# Generated by Django 2.0.6 on 2018-08-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_category_ordering_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('ordering_factor',)},
        ),
        migrations.AddField(
            model_name='sizehistory',
            name='haddad_weekly_size',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
