# Generated by Django 2.0.6 on 2018-09-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_auto_20180831_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='size',
            field=models.FloatField(default=1),
        ),
    ]
