# Generated by Django 2.0.6 on 2018-10-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_candidate_second_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeHistorySecondRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('date', models.DateTimeField()),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_history_2', to='elections.Candidate')),
            ],
        ),
    ]
